#!/bin/bash

# GopherJS Compilation
function gopherjs_compile {
    echo "GopherJS compilation in progress..."
}

# Debug build
function build_debug {
    echo "Building debug apk..."
    cordova build
}

# Release build
function build_release {
   # Build release apk
    echo "Building unsigned release apk..."
    cordova plugin rm org.apache.cordova.console
    cordova build --release android

    # Try to sign the apk
    echo "Signing apk..."
    jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
        -keystore ClaireGooglePlay.keystore \
        platforms/android/build/outputs/apk/android-release-unsigned.apk android
    
    echo "Aligning zip file..."

    if [ -e "android.apk" ]; then
        echo "Removing previous build..."
        rm -f android.apk
    fi

    /usr/local/android-sdk-linux/build-tools/22.0.1/zipalign -v 4 \
        platforms/android/build/outputs/apk/android-release-unsigned.apk android.apk
}

cd /src/www/js

echo "Go getting packages..."
go get -v
echo "GopherJS is compiling..."
gopherjs build -o="main.js" -v

cd /src

if [[ $1 != "release" ]]; then
    build_debug
else
    build_release
fi
