#!/bin/bash

for i in $*;
do
    params=" $params $i"
done

if [[ $1 == "help" ]]; then
    echo "Usage:"
    echo "cdv <command to send to the container> eg. cdv cordova create test" 
    echo "cdv apk-build [release] - builds project, omit [release] for the debug version"
else
    docker run -it \
        --rm \
        --privileged \
        -v $PWD:/src claireit/cordova $params
fi
